version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: clinica_medica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/clinica_medica
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev -- --host 0.0.0.0

  whatsapp-service:
    build: ./whatsapp-service
    ports:
      - "3001:3001"
    volumes:
      - ./whatsapp-service:/app
      - /app/node_modules
      - whatsapp_sessions:/app/sessions
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=clinica_medica
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - API_URL=http://backend:8000
      - PORT=3001
      - REMINDER_CRON_SCHEDULE=0 10 * * *
      - CLINICA_NOME=Clínica Médica Exemplo
      - CLINICA_ENDERECO=Rua Exemplo, 123 - Centro
      - CLINICA_TELEFONE=(11) 1234-5678
    depends_on:
      postgres:
        condition: service_healthy
      backend:
        condition: service_started

volumes:
  postgres_data:
  redis_data:
  whatsapp_sessions:
