services:
  # Backend FastAPI
  - type: web
    name: clinica-medica-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: PYTHONPATH
        value: /opt/render/project/src

  # PostgreSQL
  - type: pserv
    name: clinica-medica-db
    runtime: postgres
    plan: free
    ipAllowList: []

