"""Add is_active field to User

Revision ID: 19e5394cee6d
Revises: 7f5c326b4376
Create Date: 2025-10-23 14:09:56.097954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e5394cee6d'
down_revision: Union[str, Sequence[str], None] = '7f5c326b4376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('pacientes', 'is_active')
    # ### end Alembic commands ###
